[alias]
test-groth16 = "run --release --bin gnark-cli -- test --system groth16 test-data/groth16_witness.json test-data/constraints.json"
prove-groth16 = "run --release --bin gnark-cli -- prove --system groth16 test-data test-data/groth16_witness.json test-data/proof.bin"
